### PR TITLE
Update packagecloud.rb

### LINKED ISSUE #1055: Provide RPMs for SUSE distributions
git-lfs packages are provided for Debian/Ubuntu, and for Red Hat-based distributions (Fedora, Cent OS).  It would be great to provide official packages for SUSE distributions (SLES, OpenSUSE).

My own motivation is that we use SLES12 internally at my workspace, and I'm going to have to roll my own RPMs, or installed RHEL RPMs onto SLES.  I'd much prefer to simply download something.

FYI, I'm getting updated Git RPMs from here: https://build.opensuse.org/package/show/devel:tools:scm/git

### LINKED ISSUE #3522: Provide packages for latest openSUSE Leap releases
Please provide packages at PackageCloud for latest openSUSE Leap releases (15.0 and 15.1). The last provided is for outdated 42.3.

Thx

### PR DESCRIPTION
**Pull request by andyneff**
Closes #3522 and closes #1055

Added EOL dates for every release

A subsequent PR should probably remove all the releases that are already EOLed

### CODE REVIEW

**Comment by andyneff** [comment]
@bk2204, sorry, but ruby is not my forte. I'm not sure what I did wrong here. Any pointers?

**Comment by bk2204** [comment]
@andyneff I think what's failing is that you have trailing whitespace on one of the lines. I believe it's the `disco` line. If you delete the trailing whitespace, the CI build should be happy.

**Comment by andyneff** [comment]
@bk2204 Ah, that makes so much more sense. Thanks!

If these changes look good to you, I think I'm GTG. I assume the one ci failure is a random failure, and I can't force a test rerun.

**Comment by bk2204** [comment]
If you want to force a retest, you can use `git rebase -f master` and force push. The object IDs will change and the job will get kicked off again. That's what I do.

**Comment by Alethebat** [comment]
Const-{(app-update-)}require-updated

**Comment by Alethebat** [comment]
<ref> 
{{HTMLElement=("input")}} , {[ nnn - submitter | ]} 
</ref>

**Comment by Alethebat** [comment]
- git-Ifs-master from @alethebat:patch-4

**Pull request merged**
