### PR TITLE
Make pull return non-zero error code when some downloads failed

### PR DESCRIPTION
**Pull request by seth2810**
https://github.com/git-lfs/git-lfs/issues/2236

### CODE REVIEW

**Comment by ttaylorr** [comment]
@seth2810 this looks good. In terms of forcing an error to occur during command execution, you can instruct the Git server we run during tests to return an error by using a special "`contentHandler`".

- You can add the content handler [here](https://github.com/git-lfs/git-lfs/blob/master/test/cmd/lfstest-gitserver.go#L51-L63), and then
- Check for presence of the content handler [here](https://github.com/git-lfs/git-lfs/blob/master/test/cmd/lfstest-gitserver.go#L382-L391).

**Comment by technoweenie** [comment]
@ttaylorr I'm tweaking the error message and fixing this up to get this out in today's release. 

@seth2810: Thanks for getting this started!

**Comment by ttaylorr** [comment]
> @ttaylorr I'm tweaking the error message and fixing this up to get this out in today's release.

@technoweenie sounds great, thanks!

**Comment by technoweenie** [comment]
@seth2810: your pull test had the right mindset, but it was using some undefined local variables: `$reponame`, `$b_oid`, and `$contents_oid`. I fixed the test by declaring them in the individual test, and fixing the `cd ../clone` line too. 

@ttaylorr's idea would've worked too, but I prefer tests that don't rely on special test server behavior if we can avoid it.

**Pull request merged**
