### PR TITLE
remove the the duplicate work

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by ttaylorr** [comment]
@grimreaper thanks for your contribution! If would wouldn't mind signing our CLA, I think this is good to merge 👍 .

**Comment by grimreaper** [comment]
"You accepted this agreement for github/git-lfs on March 9, 2017."

**Comment by ttaylorr** [comment]
@bkeepers I've noticed a few CLA signatures not making their way through to the PR status. Is there anything I can do to diagnose this or forcibly update the status?

**Comment by technoweenie** [comment]
I think the problem is just that the ci status doesn't update until the next status run.

**Comment by ttaylorr** [comment]
I see. Going to go ahead and merge this in once CircleCI reports back.

**Comment by grimreaper** [comment]
I "edited" the diff and committed on top of it to rekick the status

**Pull request merged**
