### PR TITLE
Update custom-transfers.md

### PR DESCRIPTION
**Pull request by cbartz**
Fixed wrong key in documentation.

### CODE REVIEW

**Comment by technoweenie** [comment]
@sinbad: Does this look right to you? That definitely looks like [what `git-lfs` sends](https://github.com/git-lfs/git-lfs/blob/a0d9487e64d8059410fe9d4aa83c1cfb06477002/tq/custom.go#L88-L94), even if the [test custom adapter is looking for `event`](https://github.com/git-lfs/git-lfs/blob/a0d9487e64d8059410fe9d4aa83c1cfb06477002/test/cmd/lfstest-customadapter.go#L53-L56).

**Comment by ttaylorr** [comment]
This looks correct to me. Thanks @technoweenie for sending the relevant links
along.

LGTM, pending @cbartz signing the CLA 👍🏻.

**Comment by cbartz** [comment]
Ok. I wrote a custom transfer agent, and it didnt work with _event_ , thats how I found the bug.
I'll change my adapter to listen for _event_ and _type_ to get the terminate message. With this, it won't break once the bug fix has been released. 

Btw: In the doc file there is a line stating:

> After the initiation exchange, git-lfs will send any number of transfer requests to the stdin of the transfer process. 

Does this mean that all the transfer requests are send in one bunch? Or can it be the case that the git-lfs process waits for replies of the custom transfer adapter, and then send more transfer requests? For me, this behaviour gets not clear out of the documentation.

**Comment by sinbad** [comment]
Apologies & thanks for spotting this, I've written 2 custom transfer agents but by sheer luck this bug didn't make either of them fatally break, they just fell out of the I/O loop when the stream was closed. 

> Does this mean that all the transfer requests are send in one bunch? Or can it be the case that the git-lfs process waits for replies of the custom transfer adapter, and then send more transfer requests? For me, this behaviour gets not clear out of the documentation.

Each instance of the custom adapter will only have one transfer in flight at once. So no more requests will be sent until the adapter sends back a "complete" response for that OID (successful or not). After the "complete" response, LFS may send more requests to the same stdin. So the exchange within a single adapter instance is serial. 

Git LFS will instantiate `lfs.concurrenttransfers` instances of the adapter process and so requests will happen in parallel, just between processes.

I'll make this clearer in the docs.

**Comment by cbartz** [comment]
@sinbad : Thanks. FYI, I published my custom transfer agent [here](https://github.com/cbartz/git-lfs-swift-transfer-agent).

**Comment by sinbad** [comment]
@cbartz oh, nice!

**Pull request closed without merging**
