### PR TITLE
commands: warn if working copy is dirty

### PR DESCRIPTION
**Pull request by ttaylorr**
In 'git lfs migrate import' and 'git lfs migrate export', Git LFS makes
destructive changes to a caller's repository and therefore invokes 'git
checkout --force', which throws away local changes.

To prevent this, let's introduce a check that notifies users when they
are going to throw away local changes, and allows for the user to abort
if they do not wish to discard their local changes.

With this, a user can safely migrate over dirty repositories (i.e., in
the case that they wanted to fix a file that should have been in Git
LFS, but wasn't) without having to finagle their repository to get it
into a migrate-able state.

For users with lots of pending migrations, also teach --yes, which
allows a user to avoid the check, and instead simply prints the warning
message to STDERR.

Closes: https://github.com/git-lfs/git-lfs/issues/3123.

##

/cc @git-lfs/core 
/cc https://github.com/git-lfs/git-lfs/issues/3123, @Merglasch, @esopalumpa

### CODE REVIEW

**Comment by ttaylorr** [comment]
> This looks great! ✨ I think this needs a test that uses the
> `setup_local_branch_with_dirty_copy()` fixture, but aside from that I
> am 👍 ! I'm really glad we have this functionality now

Thanks! I added a few tests for this in 7862593c
(test/test-migrate-import.sh: test with dirty copy, 2018-07-16). This
doesn't test every case (namely: default answer, and 'y'), but I think
what's there is sufficient to go with.

Some of the other cases are a little more brittle (like sending newlines
without causing an EOF), so I'd rather leave them out instead of tending
to them.

**Comment by PastelMobileSuit** [comment]
@ttaylorr Thanks for adding the additional tests! If you feel strongly about leaving it out then I'm fine with having this merged as-is, but I would prefer if we had a single test for a `y` answer. This is going to become the standard workflow when performing a migrate, so I think it would be good to have a test so we can know if it ever breaks.

**Comment by ttaylorr** [comment]
> @ttaylorr Thanks for adding the additional tests! If you feel strongly
> about leaving it out then I'm fine with having this merged as-is, but
> I would prefer if we had a single test for a `y` answer.

I don't feel strongly; how does this look? 1bea9fd5
(test/test-migrate-import.sh: test dirty copy with 'y', 2018-07-16)

> This is going to become the standard workflow when performing a
> migrate, so I think it would be good to have a test so we can know if
> it ever breaks.

I agree, and this makes good sense to me in order to add a new test to
this effect. Let's do it! :-)

**Comment by PastelMobileSuit** [comment]
:shipit:

**Comment by ttaylorr** [comment]
Thanks for the :shipit:, I just resolved some merge conflicts and I'm
going to let CI cook this for a while and then will merge before v2.5.0.

**Pull request merged**
