### PR TITLE
Add RISC-V support

### PR DESCRIPTION
**Pull request by AaronDewes**
This adds support for the RISC-V architecture.

### CODE REVIEW

**Comment by bk2204** [comment]
Thanks for the patch, and welcome to Git LFS!  I think we'll also need a patch to `script/upload` in `categorize_arch`, which should call it `64-bit RISC-V`.

If you want to test that script, you can do so against your remote by adding a personal access token into your `~/.netrc`, updating the `REPO` field in the top of the script to your personal fork, creating an annotated tag of your local version (call it _TAG_), and running `script/upload --skip-verify TAG`.  That should create a draft release in your version for the tag that you can use to verify that the name appears as it should.

**Comment by AaronDewes** [comment]
Thanks! I tested this and it works.

**Review by bk2204 — APPROVED** [review]
Looks good, thanks.

Just to set expectations, this won't be included in v3.4.0, since we've already cut the release, but this should be included in v3.5.0.  We'll merge it once v3.4.0 is out.

**Comment by AaronDewes** [comment]
Thanks for letting me know! I saw the PR and noticed the release was scheduled for tomorrow, so I didn't expect this to make it into the release, which is unfortunate for me, but I guess I'll have to be patient and I can already build from source for now.

**Pull request merged**
