### PR TITLE
Sets -ldflags -X ... GitCommit in deb build for short-hash in version…

### LINKED ISSUE #1192: git --short commit-hash lost from version/UserAgent in 1.2.0 deb packages
- 1.1.2/packagecloud/deb `git version` : `git-lfs/1.1.2 (GitHub; linux amd64; go 1.5.3; git bf6a6c9)`
- 1.2.0/packagecloud/deb `git version` : `git-lfs/1.2.0 (GitHub; linux amd64; go 1.5.3)`
- master-54c5efa/localbuild/bin `git version` : `git-lfs/1.2.0 (GitHub; linux amd64; go 1.6; git 54c5efa)`
- master-54c5efa/localbuild/extracted-from-deb `git version` : `git-lfs/1.2.0 (GitHub; linux amd64; go 1.6)`

So this problem is in the package build and is reproducible in sandbox.

It looks like when we build from source in deb, we aren't correctly setting `-ldflags` to `-X github.com/github/git-lfs/lfs.GitCommit=<shortsha>`.  This is likely because the deb is built from source from a non-git-working-directory, which is correct, but of course does not have access to the output of `exec.Command("git", "rev-parse", "--short", "HEAD").Output()` (ref [script/build.go](https://github.com/github/git-lfs/blob/master/script/build.go#L47)).

Not sure how this regressed in 1.2.0 - possibly the deb build was improved to build from disconnected sources.

The fix is probably to inject this into the build via a new env var in [build.go](https://github.com/github/git-lfs/blob/master/script/build.go#L156) and hope that this can be passed-through to `dh_lang` helper when it launches its build.

### PR DESCRIPTION
**Pull request by javabrett**
… string. Fixed #1192.

### CODE REVIEW

**Comment by technoweenie** [comment]
This looks good to me. Can I get a sanity check from @ssgelm or @andyneff ?

**Comment by ssgelm** [comment]
I don't love this change for similar reasons as were discussed in #1156.  The deb should be possible to build from the source tarball without it needing to be a git repo.  Is there a better way we can capture the right ref without needing to be in a git repo when building the package?

**Comment by technoweenie** [comment]
The ref isn't required. So if someone is building from just a directory of files, it should just work.

> Is there a better way we can capture the right ref without needing to be in a git repo when building the package?

Would it be worth preparing a source tarball just for this purpose? 

* Teach this script to check for a local file like `./VERSION` or something
* Include the actual man pages so ruby isn't required to build.

**Comment by ssgelm** [comment]
I think a source tarball sounds like a good idea.  But as long as this still builds successfully without being in a git repo I think it's fine.

**Comment by javabrett** [comment]
I'm not currently able to get the source-tarball from `master` to `dpkg-buildpackage -us -uc`, and it fails identically with this change.  I could raise an issue for that, unless there's an existing issue or list of prerequisites for it to work.

**Comment by javabrett** [comment]
In order to build-from-tarball, would we need to replace the `ldflags` approach with some sort of `go:generate`, so that the source-code file containing the version-string with short-hash is an actual source-file in the source tarball, rather than being injected by the linker?  Guessing, this is a bit beyond my Go ...

**Comment by ttaylorr** [comment]
`github.com/github/git-lfs/lfs.GitCommit` is no longer the correct identifier (the `github` organization is now `git-lfs`, instead). @javabrett if you get a chance to look at this and update it, I would be happy to merge it 😄

**Pull request closed without merging**
