### PR TITLE
tools: use ERROR_SHARING_VIOLATION const from golang.org/x/sys/windows

### PR DESCRIPTION
**Pull request by tklauser**
Use ERROR_SHARING_VIOLATION defined in the golang.org/x/sys/windows
package instead of duplicating it in robustio_windows.go.

### CODE REVIEW

**Comment by chrisd8088** [comment]
Thanks very much for the patch; it looks like it tidies this detail up nicely and passes the CI suite, including with Go 1.11, so I'm inclined to merge it as-is unless another @git-lfs/core member has concerns.  Thanks again!

**Comment by slonopotamus** [comment]
I wonder why I didn't find it when was writing this code.

**Comment by bk2204** [comment]
No objections here.  It's possible that we didn't have that package available when this was written which may have been why we didn't notice it.

**Review by chrisd8088 — APPROVED** [review]
Very nice cleanup, thank you!

**Pull request merged**
