### PR TITLE
Testlib no global config

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by technoweenie** [comment]
Hey @mathstuf, what is the goal here? Is this a fix for anyone that uses `XDG_CONFIG_HOME` or has `$HOME/.config/git/config` already? 

Instead of copying `$TESTHOME/.gitconfig` to `$HOME/.config/git/config` AND `$HOME/.gitconfig`, what do you think about adding `unset XDG_CONFIG_HOME` instead?

**Comment by mathstuf** [comment]
That should work too. Updated.

**Comment by technoweenie** [comment]
Ah can you accept the CLA please?

**Comment by mathstuf** [comment]
Where can I get a copy of the CLA that doesn't need authentication to send to the right folks here?

**Comment by mathstuf** [comment]
OK, legal here OK'd the CLA. Closed and reopened to trigger checks again.

**Pull request merged**
