### PR TITLE
README: Add a status badge for the CircleCI build

### LINKED ISSUE #1929: Add a build badge for CircleCI to the README
The title says it all: As we have badges for Travis CI and AppVeyor, we should have one for CircleCI, too :-)

### PR DESCRIPTION
**Pull request by sschuberth**
Closes #1929.

### CODE REVIEW

**Comment by sschuberth** [comment]
@ttaylorr Done :-)

**Comment by ttaylorr** [comment]
@sschuberth thank you!

The CircleCI build failed while `brew install go`-ing, but this is definitely unrelated, so I re-ran the failing build.

cc-ing @technoweenie for a final 👍 .

**Comment by sschuberth** [comment]
@technoweenie What's the syntax for link references with images?

**Comment by ttaylorr** [comment]
> @techonweenie What's the syntax for link references with images?

I was able to get it to work with:

```markdown
| Linux | Windows | macOS |
| :---- | :------ | :---- |
[ ![Linux Build Status][1]][2] | [![Windows Build Status][3]][4] | [![Mac Build Status][5]][6] |

[1]: https://travis-ci.org/git-lfs/git-lfs.svg?branch=master
[2]: https://travis-ci.org/git-lfs/git-lfs
[3]: https://ci.appveyor.com/api/projects/status/46a5yoqc3hk59bl5/branch/master?svg=true
[4]: https://ci.appveyor.com/project/git-lfs/git-lfs/branch/master
[5]: https://circleci.com/gh/git-lfs/git-lfs.svg?style=shield&circle-token=856152c2b02bfd236f54d21e1f581f3e4ebf47ad
[6]: https://circleci.com/gh/git-lfs/git-lfs
```

Also, if I can sneak one last nit in here: we should order these alphabetically: Linux, macOS, Windows.

**Comment by sschuberth** [comment]
> we should order these alphabetically: Linux, macOS, Windows.

Done.

**Pull request merged**
