### PR TITLE
Pkg cleanup

### PR DESCRIPTION
**Pull request by technoweenie**
Bye old code :) See #1783 for discussion on the new `lfsapi` package that replaced all this.

### CODE REVIEW

**Comment by technoweenie** [comment]
Not in its current state. JSON validation in the lfsapi tests would be nice though. Let's just add that to the 2.0 milestone.

**Comment by ttaylorr** [comment]
> Not in its current state.

I'm happy to make any changes to that package as the original author :-). What
can I do to bring it up to speed and get it ready for its new home in `lfsapi`?

**Comment by technoweenie** [comment]
Following current conventions, I think the core schema validation code would live in `lfsapi`. Schemas themselves would live in the appropriate packages (`locking` for the locking endpoints, and `tq` for the batch endpoint). 

I think this is out of scope for this PR though.

**Comment by ttaylorr** [comment]
> Following current conventions, I think the core schema validation code would live in `lfsapi`. Schemas themselves would live in the appropriate packages (`locking` for the locking endpoints, and `tq` for the batch endpoint).

Sounds good. I can follow up in a future PR to re-introduce the
`SchemaValidator` as a publicly exported type in the `lfsapi` package which
would have methods:

- `Assert(t *testing.T)`, and
- `Refute(t *testing.T)`.

Other packages can use that type to validate their own schemas.

> I think this is out of scope for this PR though.

I agree 👍🏻 .

**Comment by technoweenie** [comment]
I think I'd rather have a static func like:

```go
lfsapi.VerifySchema(t, lockSchema, reader, &obj)
obj.Lock // now we know obj follows the lockSchema
```

**Comment by ttaylorr** [comment]
Sounds good to me! 👍

**Pull request merged**
