### PR TITLE
lfs: indent contents of `git lfs install`, `update`

### PR DESCRIPTION
**Pull request by ttaylorr**
This pull request indents the contents of both `git lfs install --manual` and `git lfs update` (when there are conflicting hooks).

This was suggested by @ELLIOTTCABLE in https://github.com/git-lfs/git-lfs/issues/2368.

Before implementing this, I was wary that it could cause issues where the text is copied line-wise (including the tabs) into the hook file. This is prevented by stripping leading and trailing whitespace from the given string, as well as leading whitespace on a per-line basis (via: 3705794 & fc62f34).

Closes: https://github.com/git-lfs/git-lfs/issues/2368.

---

/cc @git-lfs/core

### CODE REVIEW

**Comment by technoweenie** [comment]
Here's what it looks like now:

```sh
$ git lfs update --manual
Add the following to .git/hooks/pre-push :

#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"
Add the following to .git/hooks/post-checkout :

#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n"; exit 2; }
git lfs post-checkout "$@"
Add the following to .git/hooks/post-commit :

#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.\n"; exit 2; }
git lfs post-commit "$@"
Add the following to .git/hooks/post-merge :

#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-merge.\n"; exit 2; }
git lfs post-merge "$@"

```

Here it is with this patch:

```sh
$ script/run update --manual
Add the following to .git/hooks/pre-push :

	#!/bin/sh
	command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
	git lfs pre-push "$@"
Add the following to .git/hooks/post-checkout :

	#!/bin/sh
	command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n"; exit 2; }
	git lfs post-checkout "$@"
Add the following to .git/hooks/post-commit :

	#!/bin/sh
	command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.\n"; exit 2; }
	git lfs post-commit "$@"
Add the following to .git/hooks/post-merge :

	#!/bin/sh
	command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-merge.\n"; exit 2; }
	git lfs post-merge "$@"

```

I think the indentation adds to the readability of this command. However, any one trying to use this in their own scripts will have to fix the indentation after pasting. Is the indentation worth that? Maybe readability is more important?

I think this should at least add empty lines above each hook's `Add the following...` message. 

Also, `git lfs install --manual` doesn't work. I think it just needs [this `update` flag](https://github.com/git-lfs/git-lfs/blob/2fe41e90149a8d02c8d33e4b25f2a314bda1e346/commands/command_update.go#L62).

**Comment by ttaylorr** [comment]
> I think the indentation adds to the readability of this command. However, any one trying to use this in their own scripts will have to fix the indentation after pasting. Is the indentation worth that? Maybe readability is more important?

I agree; I definitely dig the increased readability of this command. I think the primary target here should be scriptability, with readability as a second-tier concern. That being said, since the `git lfs update` command now uses `tools.Undent` before comparing the contents of existing script files, I don't think that this will break any scripts that copy below from one `Add this to your hook` lines to the next. 

> I think this should at least add empty lines above each hook's `Add the following...` message.

I gave this a shot and it totally improved the readability of this command! Check it out after 3c509cf:

```
~/g/git-lfs (indent-install-upgrade!) $ git lfs update --manual
Add the following to .git/hooks/pre-push :
	#!/bin/sh
	command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
	git lfs pre-push "$@"

Add the following to .git/hooks/post-checkout :
	#!/bin/sh
	command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n"; exit 2; }
	git lfs post-checkout "$@"

Add the following to .git/hooks/post-commit :
	#!/bin/sh
	command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.\n"; exit 2; }
	git lfs post-commit "$@"

Add the following to .git/hooks/post-merge :
	#!/bin/sh
	command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-merge.\n"; exit 2; }
	git lfs post-merge "$@"
```

> Also, `git lfs install --manual` doesn't work. I think it just needs [this `update` flag](https://github.com/git-lfs/git-lfs/blob/2fe41e90149a8d02c8d33e4b25f2a314bda1e346/commands/command_update.go#L62).

Ah, this is a typo in the original post. I meant `git lfs update --manual` and `git lfs install`, not the other way around. That being said, I think now is as good a time as any to add `git lfs install --manual`, so I'll tag that in in a future PR.

**Comment by ttaylorr** [comment]
@technoweenie no worries! Caught that in 5f7387a.

**Comment by ELLIOTTCABLE** [comment]
Regarding indentation —

I'd say if you're copy-pasting code, fixing the indentation is basically a given (hell, lots of editors do it *for* you upon paste; especially the editors in use by the sorts of power-users that are likely to be reading the output of `--manual`.) Just a thought!

**Pull request merged**
