### PR TITLE
include ref in upload request

### PR DESCRIPTION
**Pull request by technoweenie**
Updates #969 against the current master. This was not a straight forward update because the code base has gone through a pretty major refactoring since then.
## To-do:
- [ ] Ensure we're always sending full server side refs: refs/tags/v1.0, refs/heads/master. Never client ref names.
- [ ] Integration tests that test git lfs push, git lfs fetch on repos where the local and remote branches don't match.

### CODE REVIEW

**Comment by ttaylorr** [comment]
Are the checkboxes to-do items?

**Comment by technoweenie** [comment]
Yup. Add to it if you think of anything else.

**Comment by ttaylorr** [comment]
Tentatively milestone-ing this into v2.2.0 per https://github.com/git-lfs/git-lfs/issues/2190#issuecomment-298380482.

**Comment by technoweenie** [comment]
Superseded by #2706

**Pull request closed without merging**
