### PR TITLE
updated copyright year

### PR DESCRIPTION
**Pull request by dan2468**
2020 rather than 2019 seems like the best candidate for the next release

### CODE REVIEW

**Comment by bk2204** [comment]
Hey,

I don't think we want to update the copyright year to be in the future, since the years in the copyright have legal significance as the dates when changes have been made.  Since 2020 hasn't happened yet and we can't have made any changes to Git LFS then, we can't update the copyright year yet.

**Comment by dan2468** [comment]
That’s fine.

I’m betting there won’t be another release this month, so I’ll ping again with this request on New Year’s Eve :)

**Comment by bk2204** [comment]
Sounds fine.  In the new year, I'll be back looking at Git LFS stuff on January 3, so I'll take a look then.

**Comment by dan2468** [comment]
Apologies for the merge instead of a rebase; I guess a squash of this patch is in order.

**Comment by dan2468** [comment]
This didn’t make the 2.10 release…

**Comment by bk2204** [comment]
Sorry about that.

If you want to reopen, we can merge it; just rebase it on `master` instead of merging `master` in.

**Pull request closed without merging**
