### PR TITLE
Fix: don't loop when got 401 and creds were sent (#2833)

### LINKED ISSUE #2833: bad credential leads to (almost) endless loop retrying auth / request
Hi,

happy new user of git-lfs.

```
$ git-lfs
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.1)
```

if I try to checkout, or push, or anything requiring auth with the lfs https service, but I give a bad credential (login or password), then I see that git-lfs goes into what is a very long retry-loop:

Here is an extract, so I give on purpose invalid/bad credentials..

```
12:57 $ GIT_TRACE=1 git checkout branch_foo
12:57:17.034775 git.c:344               trace: built-in: git 'checkout' 'branch_foo'
12:57:17.036042 run-command.c:334       trace: run_command: 'git-lfs clean -- '\''foobarbaz.DAT'\'''
12:57:17.036460 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git-lfs clean -- '\''foobarbaz.DAT'\''' 'git-lfs clean -- '\''foobarbaz.DAT'\'''
12:57:17.044482 trace git-lfs: run_command: 'git' version
12:57:17.050531 trace git-lfs: run_command: 'git' config -l -f /home/gregory.starck/tmp/gst_repo1_using_lfs/.lfsconfig
12:57:17.053392 trace git-lfs: run_command: 'git' config -l
12:57:17.057129 trace git-lfs: Install hook: pre-push, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/pre-push, upgrading...
12:57:17.057770 trace git-lfs: Install hook: post-checkout, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/post-checkout, upgrading...
12:57:17.058285 trace git-lfs: Install hook: post-commit, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/post-commit, upgrading...
12:57:17.058754 trace git-lfs: Install hook: post-merge, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/post-merge, upgrading...
12:57:17.061808 run-command.c:334       trace: run_command: 'git-lfs smudge -- '\''data/hugo+isaac.jpg'\'''
12:57:17.062204 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git-lfs smudge -- '\''data/hugo+isaac.jpg'\''' 'git-lfs smudge -- '\''data/hugo+isaac.jpg'\'''
12:57:17.070202 trace git-lfs: run_command: 'git' version
12:57:17.075825 trace git-lfs: run_command: 'git' config -l -f /home/gregory.starck/tmp/gst_repo1_using_lfs/.lfsconfig
12:57:17.078736 trace git-lfs: run_command: 'git' config -l
12:57:17.082542 trace git-lfs: Install hook: pre-push, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/pre-push, upgrading...
12:57:17.083157 trace git-lfs: Install hook: post-checkout, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/post-checkout, upgrading...
12:57:17.083724 trace git-lfs: Install hook: post-commit, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/post-commit, upgrading...
12:57:17.084209 trace git-lfs: Install hook: post-merge, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/post-merge, upgrading...
Downloading data/hugo+isaac.jpg (354 KB)
12:57:17.084874 trace git-lfs: tq: running as batched queue, batch size of 100
12:57:17.084999 trace git-lfs: tq: sending batch of size 1
12:57:17.085381 trace git-lfs: api: batch 1 files
12:57:17.085442 trace git-lfs: creds: git credential fill ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
Username for 'https://bitbucket.org': xx
Password for 'https://xx@bitbucket.org': 
12:57:20.407310 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.407611 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.672444 trace git-lfs: HTTP: 401
12:57:20.672659 trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
12:57:20.685392 trace git-lfs: creds: git credential cache ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
12:57:20.685406 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.685436 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.728640 trace git-lfs: HTTP: 401
12:57:20.728709 trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
12:57:20.738237 trace git-lfs: creds: git credential cache ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
12:57:20.738264 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.738343 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.780306 trace git-lfs: HTTP: 401
12:57:20.780417 trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
12:57:20.795229 trace git-lfs: creds: git credential cache ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
12:57:20.795271 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.795422 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.836481 trace git-lfs: HTTP: 401
12:57:20.836589 trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
12:57:20.851139 trace git-lfs: creds: git credential cache ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
12:57:20.851173 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.851285 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.890871 trace git-lfs: HTTP: 401
12:57:20.891010 trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
12:57:20.905927 trace git-lfs: creds: git credential cache ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
12:57:20.905961 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.906068 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.947491 trace git-lfs: HTTP: 401
12:57:20.947667 trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
12:57:20.962379 trace git-lfs: creds: git credential cache ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
12:57:20.962424 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.962687 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:21.000348 trace git-lfs: HTTP: 401
12:57:21.000461 trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
12:57:21.015164 trace git-lfs: creds: git credential cache ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
12:57:21.015199 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:21.015317 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:21.054776 trace git-lfs: HTTP: 401
```

and that continues like that retrying the request in a busy loop for well too long..

any idea how to prevent or mitigate that ? best would be to make it exit != 0 with the first encountered 401 error ?

or could something be bad on my config side ?

Thx for any pointer.

### PR DESCRIPTION
**Pull request by gst**
This should fix #2833

### CODE REVIEW

**Comment by gst** [comment]
1) the purpose is all in the title.
2) i dont know. To me when you try something and that it fail, well, retrying with same input can only lead to same result. Presumably.

**Comment by ttaylorr** [comment]
Hi @gst, thanks for your response. I gave this patch another read, and have some additional questions surrounding your change. Given the _original_ condition of the `if` statement in question, we will _always_ reject the credentials in that case.

When the request is retried, it will first reject the invalid credentials, so when it tries to fill credentials again for the retried request, it won't reuse the existing (invalid) credentials.

Given this, I am not sure if your change exhibits the intended behavior; if the problem is caused by invalid credentials, and you have changed the `if` condition to be `if creds == nil && ...`, it will never trigger that block in the first place, since the creds exist, and are therefore non-nil.

Is it possible that your credential helper is not correctly handling the "reject" command, and repeatedly providing broken credentials?

**Comment by gst** [comment]
I must confess i am not totally sure it s the exact fix i actually tried with expected behavior. ;)
I could not recompile on second try and had not willingless to debug go issues at the time.

**Comment by ttaylorr** [comment]
Hi again, @gst. Not a worry. I am going to close this for now, operating under the assumption that this is the fault of a misbehaving credential helper. If you would like to work on this again in the future, please do not hesitate to let me know! Thanks.

**Comment by stffabi** [comment]
@ttaylorr I've done a more in-depth analysis of the problem in [#2833](https://github.com/git-lfs/git-lfs/issues/2833#issuecomment-374254778) why it ended up in an endless loop.

**Comment by ttaylorr** [comment]
Sounds good, @stffabi (& @gst) -- glad that this is no longer an issue!

**Pull request closed without merging**
