### PR TITLE
git/githistory/log: teach Durable() to Task

### PR DESCRIPTION
**Pull request by ttaylorr**
This pull request teaches a new `Task` type to the `github.com/git-lfs/git-lfs/git/githistory/log` package: `DurableTask`.

A `DurableTask` ensures that all log `<-Update()` reads are logged to the `sink io.Writer`, regardless of throttling conditions. This required for multi-line log updates (like output from `git-ref-update(1)`) where all log lines are important.

---

/cc @git-lfs/core 
/refs #2146 #2329

### CODE REVIEW

**Comment by technoweenie** [comment]
Why is this needed? If the tasks need to be durable, then they probably don't need to be throttled in the first place. Do only some of the tasks need this?

**Comment by ttaylorr** [comment]
> Why is this needed? If the tasks need to be durable, then they probably don't need to be throttled in the first place. Do only some of the tasks need this?

Good question 😄 Only some of the tasks need this. For instance, the `*PercentageTask` writes updates every time `Count()` is called, and usually gets throttled. The `*ListTask` type (see: https://github.com/git-lfs/git-lfs/pull/2335) yields updates at an unknown rate, but it's important that all updates are logged. In other words, `ListTask` satisfies `DurableTask`, but `*PercentageTask` does not,.

**Comment by technoweenie** [comment]
Ah, that makes sense after looking at that PR. I would just add `Durable()` to the base Task interface, since there are only a few task types. What do you think about `Throttled()` for a name instead of `Durable()`?

**Comment by ttaylorr** [comment]
> Ah, that makes sense after looking at that PR.

Thanks for taking a look, and sorry for not explaining things more thoroughly in this PR.

> I would just add `Durable()` to the base Task interface, since there are only a few task types.

Good call, I like the explicitness of being able to declare that a task is `Durable()` or not per task. I added that in a7a99e5, 8c64a43 & 5223586.

> What do you think about `Throttled()` for a name instead of `Durable()`?

I think I prefer the `Durable()` name, since `Throttled()` feels like a negated conditional.

**Comment by technoweenie** [comment]
I just don't think `Durable` accurately describes what is happening. Maybe I'm just used to seeing that word in the context of a data store.

**Pull request merged**
