### PR TITLE
Add nil-check on defer block of DoTransfer()

### PR DESCRIPTION
**Pull request by exceed-alae**
If os.OpenFile() returns error then variable "f" is nil, so support this case

### CODE REVIEW

**Comment by slonopotamus** [comment]
Ugh... Seems like things are not that simple.

The relevant code is:

    f, err = os.OpenFile(f.Name(), os.O_RDWR, 0644)

So, there is a filename that should be deleted (`f.Name()` *before* call to `OpenFile`), but it gets lost if `OpenFile` fails.

**Comment by exceed-alae** [comment]
> So, there is a filename that should be deleted (f.Name() before call to OpenFile), but it gets lost if OpenFile fails and overwrites f with nil.

I see ... that's right... I'm going to push new patch.

**Comment by slonopotamus** [comment]
@exceed-ale: just curious: did you find this problem by reading through the code or actually hit it in real-world scenario? Even after your fix, hitting this codepath means that download has failed in a kinda unexpected way. The bug you're fixing was introduced during #3826 that has severely changed this code to deal with concurrent git-lfs processes downloading to the same LFS storage. So I'm interested in conditions that trigger this code to fail because that might mean that measures taken to fix concurrent problems were not enough.

**Comment by exceed-alae** [comment]
@slonopotamus That problem occured when I was testing lfs.storage sharing by multi user. (2.9.0 for WIndows. I've set lfs.storage to //MACHINE/SHARE/)
The exact situation at the time of that problem occured have not been confirmed. But I think so that same object was accessed on same timing by different user.

**Pull request merged**
