### PR TITLE
release: v2.5.0

### PR DESCRIPTION
**Pull request by ttaylorr**
##

/cc @git-lfs/core @git-lfs/releases

### CODE REVIEW

**Comment by larsxschneider** [comment]
🎉 👍 😄

**Comment by dscho** [comment]
Could you maybe automate the release engineering, also to guarantee a consistent file naming and release notes? For v2.5.0, the .zip file has a `v` in front of the version number, which the previous version had not. And the SHA-256s are now listed *before* the files, previously they were listed afterwards. This broke the automated upgrade script I have to maintain all kinds of 3rd-party components I bundle in Git for Windows, so I had to spend some quality time today to fix it...

**Comment by ttaylorr** [comment]
> Could you maybe automate the release engineering, also to guarantee a consistent file naming and release notes?

Thanks for the note. Automating the release process is a to-do item on my list, but achieving this is not a straightforward process. Thanks for including Git LFS in GFW, and for fixing some inconsistencies between releases.

**Comment by dscho** [comment]
Technically, I did not fix any inconsistency at all. I worked around them, by reacting to failures of the upgrade job.

**Comment by dscho** [comment]
And now I will work around the next inconsistency, which is that the SHA-256 sums are once again listed *below*, rather than *above* the file names. Seriously, once you automate that, you will relieve me of a ton of work with every Git LFS release.

**Comment by dscho** [comment]
For the record, this particular inconsistency is worked around in the Git for Windows project by this commit: https://github.com/git-for-windows/build-extra/commit/cf35e4915fb4d67810cf9fb26718c502a80a5218 (and if that diff scares you, it should: this is the consequence non-automated Git LFS releases has on Git for Windows alone; I do not want to muse about other the impact on other projects...).

**Comment by ttaylorr** [comment]
> And now I will work around the next inconsistency, which is that the
> SHA-256 sums are once again listed *below*, rather than *above* the
> file names.

Sorry, and we appreciate you working around the inconsistencies between
releases. In the future, we'll do our best to make sure that the
signature is below rather than above the filename, such that the format
is:

    **git-lfs-$(GOOS)-$(GOARCH)-v$(VERSION).tar.gz**
    $shasum

and:

    **git-lfs-windows-$(GOARCH)-v$(VERSION).zip**
    $shasum

This release adopted the above styling after you [pointed out][1] that
we had been inconsistent in our usual styling with the v2.5.0 release.

You can expect the above (modulo some human error) in future releases.

[1]: https://github.com/git-lfs/git-lfs/pull/3150#issuecomment-408456045

**Pull request merged**
